# .github/workflows/compare-file.yml
name: Generate HTML Diff Between Branches

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare (e.g., main)'
        required: true
        default: 'main'
      compare_branch:
        description: 'Branch to compare against base'
        required: true
        default: 'dev'
      file_path:
        description: 'Path to the file to compare'
        required: true
        default: 'home.txt'

jobs:
  html-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout compare branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.compare_branch }}

      - name: Fetch file from base branch
        run: |
          git fetch origin ${{ github.event.inputs.base_branch }}
          git show origin/${{ github.event.inputs.base_branch }}:${{ github.event.inputs.file_path }} > base.tmp

      - name: Copy compare branch file
        run: |
          cp ${{ github.event.inputs.file_path }} compare.tmp

      - name: Generate diff.html via vimdiff
        run: |
          vimdiff base.tmp compare.tmp << 'EOF'
          :TOhtml
          :w! diff.html
          :qa!
          EOF
          sed -i 's/\.DiffAdd\s*{[^}]*}/.DiffAdd { background-color: #ccffcc; color: #000000; padding-bottom: 1px; }/' diff.html
          sed -i 's/\.DiffDelete\s*{[^}]*}/.DiffDelete { background-color: #ffcccc; color: #000000; padding-bottom: 1px; font-weight: bold; }/' diff.html
          sed -i 's/\.DiffChange\s*{[^}]*}/.DiffChange { background-color: #ffffcc; color: #000000; padding-bottom: 1px; }/' diff.html
          sed -i 's/\.DiffText\s*{[^}]*}/.DiffText { background-color: #ccffff; color: #000000; padding-bottom: 1px; font-weight: bold; }/' diff.html



      - name: Upload HTML diff
        uses: actions/upload-artifact@v4
        with:
          name: html-diff
          path: diff.html
