name: Generate Colored HTML Diff

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch (e.g., main)'
        required: true
        default: 'main'
      compare_branch:
        description: 'Compare branch (e.g., dev)'
        required: true
        default: 'dev'
      file_path:
        description: 'File path (e.g., home.txt)'
        required: true
        default: 'home.txt'

jobs:
  diff-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compare branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.compare_branch }}

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.inputs.base_branch }}

      - name: Save base and compare files
        run: |
          git show origin/${{ github.event.inputs.base_branch }}:${{ github.event.inputs.file_path }} > base_file.txt
          cp ${{ github.event.inputs.file_path }} compare_file.txt

      - name: Generate unified diff
        run: |
          diff -u base_file.txt compare_file.txt > diff.patch || true

      - name: Install diff2html-cli
        run: |
          npm install -g diff2html-cli

      - name: Generate HTML diff with colors
        run: |
          diff2html -i file -s side -F diff.html diff.patch

      - name: Upload HTML diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: colored-html-diff
          path: diff.html
