# .github/workflows/compare-file.yml
name: Compare File Between Branches

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare (e.g., main)'
        required: true
        default: 'main'
      compare_branch:
        description: 'Branch to compare against base'
        required: true
        default: 'dev'
      file_path:
        description: 'Path of the file to compare'
        required: true
        default: 'home.txt'

jobs:
  compare-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout compare_branch (default checked-out branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.compare_branch }}

      - name: Extract file from base_branch
        run: |
          echo "Extracting file from base branch: ${{ github.event.inputs.base_branch }}"
          git fetch origin ${{ github.event.inputs.base_branch }}
          git show origin/${{ github.event.inputs.base_branch }}:${{ github.event.inputs.file_path }} > base_file.txt

      - name: Save file from compare_branch
        run: |
          echo "Saving file from compare branch: ${{ github.event.inputs.compare_branch }}"
          cp ${{ github.event.inputs.file_path }} compare_file.txt
